CRUD_Vehicles/Models/Vehicle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Week7CodeAssessment.Models
{
    public partial class Vehicle
    {
        public Vehicle()
        {
            Claims = new HashSet<Claim>();
        }

        public int Id { get; set; }
        public string? Brand { get; set; }
        public string? Vin { get; set; }
        public string? Color { get; set; }

        [Range(1886, 2100, ErrorMessage = "Enter a year between 1886 and 2100.")]
        public int? Year { get; set; }

        public int? OwnerId { get; set; }

    

        public virtual Owner? Owner { get; set; }
        public virtual ICollection<Claim> Claims { get; set; }
    }
}

CRUD_Vehicles/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Week7CodeAssessment.Models;

namespace Week7CodeAssessment.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly crudContext _context;

        public VehiclesController(crudContext context)
        {
            _context = context;
        }

        // GET: Vehicles
        public async Task<IActionResult> Index(String searchOwnerId)
        {
            var vehicles = from vehicle in _context.Vehicles select vehicle;

            if (!String.IsNullOrEmpty(searchOwnerId))
            {
                             vehicles = vehicles.Where(s => s.OwnerId.ToString()!.Contains(searchOwnerId));
            }

            var week7codeContext = _context.Vehicles.Include(v => v.Owner);
            return View(await vehicles.ToListAsync());
        }

        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles
                .Include(v => v.Owner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // GET: Vehicles/Create
        public IActionResult Create()
        {
            ViewData["OwnerId"] = new SelectList(_context.Owners, "Id", "Id");
            return View();
        }

        // POST: Vehicles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Brand,Vin,Color,Year,OwnerId")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vehicle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["OwnerId"] = new SelectList(_context.Owners, "Id", "Id", vehicle.OwnerId);
            return View(vehicle);
        }

        // GET: Vehicles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles.FindAsync(id);
            if (vehicle == null)
            {
                return NotFound();
            }
            ViewData["OwnerId"] = new SelectList(_context.Owners, "Id", "Id", vehicle.OwnerId);
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Brand,Vin,Color,Year,OwnerId")] Vehicle vehicle)
        {
            if (id != vehicle.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OwnerId"] = new SelectList(_context.Owners, "Id", "Id", vehicle.OwnerId);
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles
                .Include(v => v.Owner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vehicles == null)
            {
                return Problem("Entity set 'week7codeContext.Vehicles'  is null.");
            }
            var vehicle = await _context.Vehicles.FindAsync(id);
            if (vehicle != null)
            {
                _context.Vehicles.Remove(vehicle);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(int id)
        {
          return _context.Vehicles.Any(e => e.Id == id);
        }
    }
}

CRUD_Vehicles/Views/Vehicles/Create.cshtml
@model Week7CodeAssessment.Models.Vehicle

@{
    ViewData["Title"] = "Create";
}

<h1>CREATE VEHICLE</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"><b>BRAND</b></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vin" class="control-label"><b>VIN</b></label>
                <input asp-for="Vin" class="form-control" />
                <span asp-validation-for="Vin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"><b>COLOR</b></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"><b>YEAR</b></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"><b>OWNER ID</b></label>
                <select asp-for="OwnerId" class ="form-control" asp-items="ViewBag.OwnerId"></select>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br/>
<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

CRUD_Vehicles/Views/Vehicles/Delete.cshtml
@model Week7CodeAssessment.Models.Vehicle

@{
    ViewData["Title"] = "Delete";
}

<h1>DELETE VEHICLE</h1>
<br/>
<h3>Are you sure you want to delete this vehicle?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
             BRAND
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            VIN
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vin)
        </dd>
        <dt class = "col-sm-2">
            COLOR
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            YEAR
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            OWNER ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OwnerId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

CRUD_Vehicles/Views/Vehicles/Details.cshtml
@model Week7CodeAssessment.Models.Vehicle

@{
    ViewData["Title"] = "Details";
}

<h1>DETAILS VEHICLE</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            BRAND
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            VIN
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vin)
        </dd>
        <dt class = "col-sm-2">
            COLOR
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            YEAR
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            OWNER ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OwnerId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-warning">Edit</a> |
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

CRUD_Vehicles/Views/Vehicles/Edit.cshtml
@model Week7CodeAssessment.Models.Vehicle

@{
    ViewData["Title"] = "Edit";
}

<h1>EDIT VEHICLE</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Brand" class="control-label"><b>BRAND</b></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vin" class="control-label"><b>VIN</b></label>
                <input asp-for="Vin" class="form-control" />
                <span asp-validation-for="Vin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"><b>COLOR</b></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"><b>YEAR</b></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"><b>OWNER ID</b></label>
                <select asp-for="OwnerId" class="form-control" asp-items="ViewBag.OwnerId"></select>
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br/>
<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

CRUD_Vehicles/Views/Vehicles/Index.cshtml
@model IEnumerable<Week7CodeAssessment.Models.Vehicle>

@{
    ViewData["Title"] = "Index";
}

<h1>ALL VEHICLES</h1>
<br />
<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>

<form asp-controller="Vehicles" asp-action="Index" method="get">
    <p>
        Search by Owner ID: <input type="text" name="searchOwnerId" class="form-text" />
        <input type="submit" value="Search" class="btn btn-sm btn-dark" />
    </p>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                BRAND
            </th>
            <th>
                VIN
            </th>
            <th>
                COLOR
            </th>
            <th>
                YEAR
            </th>
            <th>
                OWNER ID
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OwnerId)
            </td>
            <td>
                    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>