CRUD_Vehicles/Models/Claim.cs
using System;
using System.Collections.Generic;

namespace Week7CodeAssessment.Models
{
    public partial class Claim
    {
        public int Id { get; set; }
        public string? Description { get; set; }
        public string? Status { get; set; }
        public DateTime? Date { get; set; }
        public int? VehicleId { get; set; }

        public virtual Vehicle? Vehicle { get; set; }
    }
}

CRUD_Vehicles/Controllers/ClaimsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Week7CodeAssessment.Models;

namespace Week7CodeAssessment.Controllers
{
    public class ClaimsController : Controller
    {
        private readonly crudContext _context;

        public ClaimsController(crudContext context)
        {
            _context = context;
        }

        // GET: Claims
        public async Task<IActionResult> Index(String searchVehiclesId)
        {
            var claims = from claim in _context.Claims select claim;


            if (!String.IsNullOrEmpty(searchVehiclesId))
            {
                claims = claims.Where(s => s.VehicleId.ToString()!.Contains(searchVehiclesId));
            }

            var week7codeContext = _context.Claims.Include(c => c.Vehicle);
            return View(await claims.ToListAsync());
        }

        // GET: Claims/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Claims == null)
            {
                return NotFound();
            }

            var claim = await _context.Claims
                .Include(c => c.Vehicle)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (claim == null)
            {
                return NotFound();
            }

            return View(claim);
        }

        // GET: Claims/Create
        public IActionResult Create()
        {
            ViewData["VehicleId"] = new SelectList(_context.Vehicles, "Id", "Id");
            return View();
        }

        // POST: Claims/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,Status,Date,VehicleId")] Claim claim)
        {
            if (ModelState.IsValid)
            {
                _context.Add(claim);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["VehicleId"] = new SelectList(_context.Vehicles, "Id", "Id", claim.VehicleId);
            return View(claim);
        }

        // GET: Claims/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Claims == null)
            {
                return NotFound();
            }

            var claim = await _context.Claims.FindAsync(id);
            if (claim == null)
            {
                return NotFound();
            }
            ViewData["VehicleId"] = new SelectList(_context.Vehicles, "Id", "Id", claim.VehicleId);
            return View(claim);
        }

        // POST: Claims/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,Status,Date,VehicleId")] Claim claim)
        {
            if (id != claim.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(claim);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClaimExists(claim.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["VehicleId"] = new SelectList(_context.Vehicles, "Id", "Id", claim.VehicleId);
            return View(claim);
        }

        // GET: Claims/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Claims == null)
            {
                return NotFound();
            }

            var claim = await _context.Claims
                .Include(c => c.Vehicle)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (claim == null)
            {
                return NotFound();
            }

            return View(claim);
        }

        // POST: Claims/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Claims == null)
            {
                return Problem("Entity set 'week7codeContext.Claims'  is null.");
            }
            var claim = await _context.Claims.FindAsync(id);
            if (claim != null)
            {
                _context.Claims.Remove(claim);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClaimExists(int id)
        {
          return _context.Claims.Any(e => e.Id == id);
        }
    }
}

CRUD_Vehicles/Views/Claims/Create.cshtml
@model Week7CodeAssessment.Models.Claim

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Claim</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"><b>DESCRIPTION</b></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"><b>STATUS</b></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"><b>CLAIM DATE</b></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VehicleId" class="control-label"><b>VEHICLE ID</b></label>
                <select asp-for="VehicleId" class ="form-control" asp-items="ViewBag.VehicleId"></select>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br/>
<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

CRUD_Vehicles/Views/Claims/Delete.cshtml
@model Week7CodeAssessment.Models.Claim

@{
    ViewData["Title"] = "Delete";
}

<h1>DELETE CLAIM</h1>
<br/>
<h3>Are you sure you want to delete this claim?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            DESCRIPTION
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            STATUS
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            CLAIM DATE
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            VEHICLE ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehicleId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

CRUD_Vehicles/Views/Claims/Details.cshtml
@model Week7CodeAssessment.Models.Claim

@{
    ViewData["Title"] = "Details";
}

<h1>DETAILS CLAIM</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            DESCRIPTION
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            STATUS
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            CLAIM DATE
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            VEHICLES ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehicleId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id"  class="btn btn-warning">Edit</a> |
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

CRUD_Vehicles/Views/Claims/Edit.cshtml
@model Week7CodeAssessment.Models.Claim

@{
    ViewData["Title"] = "Edit";
}

<h1>EDIT CLAIM</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"><b>DESCRIPTION</b></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"><b>STATUS</b></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"><b>CLAIM DATE</b></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VehicleId" class="control-label"><b>VEHICLE ID</b></label>
                <select asp-for="VehicleId" class="form-control" asp-items="ViewBag.VehicleId"></select>
                <span asp-validation-for="VehicleId" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
       
        </form>
    </div>
</div>
<br/>
<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

CRUD_Vehicles/Views/Claims/Index.cshtml
@model IEnumerable<Week7CodeAssessment.Models.Claim>

@{
    ViewData["Title"] = "Index";
}

<h1>ALL CLAIMS</h1>
<br />
<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>


<form asp-controller="Claims" asp-action="Index" method="get">
    <p>
        Search by Vehicle ID: <input type="text" name="searchVehiclesId" class="form-text" />
        <input type="submit" value="Search" class="btn btn-sm btn-dark" />
    </p>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                DESCRIPTION
            </th>
            <th>
                STATUS
            </th>
            <th>
                CLAIM DATE
            </th>
            <th>
                VEHICLE ID
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleId)
            </td>
            <td>
                    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>