CRUD_Vehicles/Models/Owner.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Diagnostics.Metrics;

namespace Week7CodeAssessment.Models
{
    public partial class Owner
    {
        public Owner()
        {
            Vehicles = new HashSet<Vehicle>();
        }

        public int Id { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? DriverLicense { get; set; }

        public virtual ICollection<Vehicle> Vehicles { get; set; }


    }
}

CRUD_Vehicles/Controllers/OwnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Week7CodeAssessment.Models;

namespace Week7CodeAssessment.Controllers
{
    public class OwnersController : Controller
    {
        private readonly crudContext _context;

        public OwnersController(crudContext context)
        {
            _context = context;
        }

        // GET: Owners
        public async Task<IActionResult> Index(String OwnerId)
        {
            var owners = from owner in _context.Owners select owner;

            if (!String.IsNullOrEmpty(OwnerId))
            {
                owners = owners.Where(s => s.Id.ToString()!.Contains(OwnerId));
            }
            var week7codeContext = _context.Owners.Include(v => v.Id);
            return View(await owners.ToListAsync());
        }

        // GET: Owners/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Owners == null)
            {
                return NotFound();
            }

            var owner = await _context.Owners
                .FirstOrDefaultAsync(m => m.Id == id);
            if (owner == null)
            {
                return NotFound();
            }

            return View(owner);
        }

        // GET: Owners/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Owners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,DriverLicense")] Owner owner)
        {
            if (ModelState.IsValid)
            {
                _context.Add(owner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(owner);
        }

        // GET: Owners/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Owners == null)
            {
                return NotFound();
            }

            var owner = await _context.Owners.FindAsync(id);
            if (owner == null)
            {
                return NotFound();
            }
            return View(owner);
        }

        // POST: Owners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,DriverLicense")] Owner owner)
        {
            if (id != owner.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(owner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OwnerExists(owner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(owner);
        }

        // GET: Owners/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Owners == null)
            {
                return NotFound();
            }

            var owner = await _context.Owners
                .FirstOrDefaultAsync(m => m.Id == id);

            if (owner == null)
            {
                return NotFound();
            }

            return View(owner);
        }

        // POST: Owners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Owners == null)
            {
                return Problem("Entity set 'week7codeContext.Owners'  is null.");
            }
            var owner = await _context.Owners.FindAsync(id);
            if (owner != null)
            {
                _context.Owners.Remove(owner);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OwnerExists(int id)
        {
          return _context.Owners.Any(e => e.Id == id);
        }
    }
}

CRUD_Vehicles/Views/Owners/Create.cshtml
@model Week7CodeAssessment.Models.Owner

@{
    ViewData["Title"] = "Create";
}

<h1>CREATE OWNER</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DriverLicense" class="control-label"></label>
                <input asp-for="DriverLicense" class="form-control" />
                <span asp-validation-for="DriverLicense" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br/>
<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

CRUD_Vehicles/Views/Owners/Delete.cshtml
@model Week7CodeAssessment.Models.Owner

@{
    ViewData["Title"] = "Delete";
}

<h1>DELETE OWNER</h1>
<br/>
<h3>Are you sure you want to delete this owner?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
                FIRST NAME
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
                LAST NAME
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
                DRIVER LICENSE
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DriverLicense)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

CRUD_Vehicles/Views/Owners/Details.cshtml
@model Week7CodeAssessment.Models.Owner

@{
    ViewData["Title"] = "Details";
}

<h1>DETAILS OWNER</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            FIRST NAME
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            LAST NAME
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            DRIVER LICENSE
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DriverLicense)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-warning">Edit</a> |
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

CRUD_Vehicles/Views/Owners/Edit.cshtml
@model Week7CodeAssessment.Models.Owner

@{
    ViewData["Title"] = "Edit";
}

<h1>EDIT OWNER</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"><b>FIRST NAME</b></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"><b>LAST NAME</b></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DriverLicense" class="control-label"><b>DRIVER LICENSE</b></label>
                <input asp-for="DriverLicense" class="form-control" />
                <span asp-validation-for="DriverLicense" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
 <br/>
<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

CRUD_Vehicles/Views/Owners/Index.cshtml
@model IEnumerable<Week7CodeAssessment.Models.Owner>

@{
    ViewData["Title"] = "Index";
}

<h1>ALL OWNERS</h1>
<br/>
<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>


<form asp-controller="Owners" asp-action="Index" method="get">
    <p>
        Search by Owner ID: <input type="text" name="OwnerId" class="form-text" />
        <input type="submit" value="Search" class="btn btn-sm btn-dark" />
    </p>
</form>



<table class="table">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                FIRST NAME
            </th>
            <th>
                LAST NAME
            </th>
            <th>
                DRIVER LICENSE
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DriverLicense)
            </td>
            <td>
                    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>